var data = {
    "2018":{
        "enero":{
              "5":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor",
                                          "img" : "png"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "16":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        },    
        "agosto":{
              "5":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "23":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        },
        "setiembre":{
              "22":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "27":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "30":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        },
        "diciembre":{
              "5":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "16":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        }
      },
    "2019": {
        "enero":{
              "5":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "16":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        },    
        "agosto":{
              "5":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    },
              "16":{
                  "cumpleano":{
                                "Ruben":{ 
                                          "cargo":"Supervisor"
                                  },
                                  "Ricardo": {
                                              "cargo":"Asesor"}
                                  },
                  "evento":{
                              "dato":"1"
                            },
                  "comunicado":{
                            "dato":"1"
                          }
                    }
        }      
    }  
}